#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/config"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$PLUGIN_AVAILABLE_PATH/certs/functions"
source "$PLUGIN_AVAILABLE_PATH/config/functions"
source "$_DIR/internal-functions"

get_nginx_location() {
  declare desc="check that nginx is at the expected location and return it"
  fn-nginx-custom-nginx-location
}

get_app_proxy_type() {
  local APP="$1"
  type=$(plugn trigger proxy-type "$APP")
  proxy_is_enabled=$(plugn trigger proxy-is-enabled "$APP")
  if [[ "$proxy_is_enabled" == "false" ]]; then
    echo ""
  fi
  echo "$type"
}

restart_nginx() {
  declare desc="restart nginx for given distros"
  declare APP="$1"

  nginx_restart_command="$(fn-get-property --app "$APP" --global "nginx-restart-command")"
  if [[ -n "$nginx_restart_command" ]]; then
    eval "$nginx_restart_command"
    return $?
  fi

  if fn-nginx-custom-uses-openresty; then
    command="/usr/bin/systemctl reload openresty"
  else 
    command="/usr/bin/systemctl reload nginx"
  fi

  set -x
  trap "set +x" EXIT

  run_with_sudo="$(fn-get-property --app "$APP" --global "nginx-restart-command-run-with-sudo")"
  if [[ "$run_with_sudo" == "true" ]] || [[ -z "$run_with_sudo" ]]; then
    sudo $command
  else
    $command
  fi

}

nginx_build_config() {
  declare desc="build nginx config to proxy app containers using sigil"
  declare APP="$1"

  DOKKU_APP_LISTENERS="$(plugn trigger network-get-listeners "$APP" "web" | xargs)"

  echo -e "DOKKU_APP_LISTENERS: $DOKKU_APP_LISTENERS"

  plugn trigger ports-configure "$APP"
  local PROXY_PORT=$(config_get "$APP" DOKKU_PROXY_PORT)
  local PROXY_SSL_PORT=$(config_get "$APP" DOKKU_PROXY_SSL_PORT)
  echo -e "PROXY_PORT: $PROXY_PORT"
  echo -e "PROXY_SSL_PORT: $PROXY_SSL_PORT"

  local PORT_MAP PROXY_PORT_MAP proxy_port_map
  while read -r PORT_MAP; do
    echo -e "PORT_MAP: $PORT_MAP"

    local PROXY_UPSTREAM_SCHEME="$(awk -F ':' '{ print $1 }' <<<"$PORT_MAP")"

    proxy_port_map="$proxy_port_map $PORT_MAP"

    local PROXY_UPSTREAM_PORT="$(awk -F ':' '{ print $3 }' <<<"$PORT_MAP")"
    if [[ "$(is_val_in_list "$PROXY_UPSTREAM_PORT" "$PROXY_UPSTREAM_PORTS" " ")" == "false" ]]; then
      local PROXY_UPSTREAM_PORTS+="$PROXY_UPSTREAM_PORT "
    fi
  done < <(plugn trigger ports-get "$APP")
  
  PROXY_PORT_MAP="$(echo "$proxy_port_map" | xargs)"

  local PROXY_UPSTREAM_PORTS="$(echo "$PROXY_UPSTREAM_PORTS" | xargs)"

  nginx_test_command="sudo nginx -t"
  if fn-nginx-custom-uses-openresty; then
    nginx_test_command="sudo openresty -t"
  fi

  export DOKKU_APP_CONTAINER_LABELS="$(app_container_get_labels "$APP")"
  export DOKKU_APP_LISTENERS PROXY_PORT PROXY_PORT_MAP PROXY_UPSTREAM_PORTS
  export PROXY_CACHE_ON_DISK_ROOT_PATH="$(fn-nginx-custom-proxy-cache-on-disk-root-path "$APP")"
  export PROXY_CACHE_IN_MEM_ROOT_PATH="$(fn-nginx-custom-proxy-cache-in-mem-root-path "$APP")"
  export FASTCGI_CACHE_ON_DISK_ROOT_PATH="$(fn-nginx-custom-fastcgi-cache-on-disk-root-path "$APP")"
  export FASTCGI_CACHE_IN_MEM_ROOT_PATH="$(fn-nginx-custom-fastcgi-cache-in-mem-root-path "$APP")"
  export PROXY_CACHE_DEFAULT_FLAGS="$(fn-nginx-custom-proxy-cache-default-flags "$APP")"
  export FASTCGI_CACHE_DEFAULT_FLAGS="$(fn-nginx-custom-fastcgi-cache-default-flags "$APP")"
  export PROXY_CACHE_DEFAULT_KEY_ZONE_SIZE="$(fn-nginx-custom-proxy-cache-default-key-zone-size "$APP")"
  export FASTCGI_CACHE_DEFAULT_KEY_ZONE_SIZE="$(fn-nginx-custom-fastcgi-cache-default-key-zone-size "$APP")"
  export DOKKU_APP_CONTAINER_WORKING_DIR_PATH="$(app_container_get_working_dir_path "$APP")"
  export NGINX_ADD_HEADER_MODE="$(fn-nginx-custom-add-header-mode "$APP")"
  export DOKKU_APP_STORAGE_DIR="${DOKKU_STORAGE_DIR}/${APP}"
  "$_DIR/nginx-config-builder" \
    -app-name "$APP" \
    -config-file-path "${DATA_DIRECTORY}/app-$APP/nginx-custom-config-yaml/$(fn-nginx-custom-config-file "$APP")" \
    -dokku-data-root-directory "${DATA_DIRECTORY}/app-${APP}" \
    -nginx-test-command "$nginx_test_command"
}

app_container_get() {
    declare APP_NAME="$1"

    container=$(docker ps -q --no-trunc --filter "label=org.label-schema.vendor=dokku" --filter "name=$APP_NAME.*.*" | head -n 1)
    if [[ -z "$container" ]]; then
        dokku_log_fail "Container not found for $APP"
    fi

    echo "$container"
}

app_container_get_merged_dir_path() {
    declare APP_NAME="$1"

    container=$(app_container_get "$APP_NAME")
    merged_dir_path="$(docker inspect --format='{{.GraphDriver.Data.MergedDir}}' "$container")"
    echo "$merged_dir_path"
}

app_container_get_working_dir_path() {
    declare APP_NAME="$1"

    container=$(app_container_get "$APP_NAME")
    merged_dir_path=$(app_container_get_merged_dir_path "$APP_NAME")
    image="$(docker inspect --format='{{.Image}}' "$container")"
    working_dir_path="$merged_dir_path/$(docker image inspect --format "{{.Config.WorkingDir}}" $image)"
    echo "$working_dir_path"
}

app_container_get_labels() {
    declare APP_NAME="$1"

    container=$(app_container_get "$APP_NAME")
    docker inspect --format='{{json .Config.Labels}}' "$container"
}