#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$_DIR/config"
source "$_DIR/functions"
source "$_DIR/internal-functions"

trigger-nginx-custom-core-post-delete() {
  declare desc="${PROXY_NAME} core-post-delete plugin trigger"
  declare trigger="nginx_custom_post_deploy"
  declare APP="$1"
  local HAS_NETWORK_CONFIG

  log_info "Running trigger trigger-nginx-custom-core-post-delete"
  log_info "Proxy type:" "$(get_app_proxy_type "$APP"); PROXY_NAME: $PROXY_NAME"

  if ! is_this_the_proxy "$APP"; then
    log_info "[trigger-nginx-custom-core-post-delete] Quitting"
    return
  fi
  
  data_dir="$(fn-get-data-dir $APP)/app-${APP}/"
  test -d "$data_dir" && rm -rf "$data_dir"

  nginx_test_command="$(get_nginx_test_command)"
  $nginx_test_command || dokku_log_fail "nginx config test failed"
  restart_nginx "$APP" || dokku_log_fail "nginx restart failed"
}

trigger-nginx-custom-core-post-delete "$@"