#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"
source "$_DIR/config"
source "$_DIR/functions"

trigger-nginx-custom-core-post-delete() {
  declare desc="${PROXY_NAME} core-post-delete plugin trigger"
  declare trigger="nginx_custom_post_deploy"
  declare APP="$1"
  local HAS_NETWORK_CONFIG

  echo "Proxy type:" "$(get_app_proxy_type "$APP"); PROXY_NAME: $PROXY_NAME"

  if [[ "$(get_app_proxy_type "$APP")" != "$PROXY_NAME" ]]; then
    echo "[trigger-nginx-custom-core-post-delete] Quitting"
    return
  fi
  
  rm -rf "$(fn-get-data-dir $APP)/app-${APP}"
  nginx_test_command="sudo nginx -t"
  if fn-nginx-custom-uses-openresty; then
    nginx_test_command="sudo openresty -t"
  fi
  $nginx_test_command || dokku_log_fail "nginx config test failed"
  restart_nginx "$APP" || dokku_log_fail "nginx restart failed"
}

trigger-nginx-custom-core-post-delete "$@"