#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/config"
source "$_DIR/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

trigger-nginx-custom-proxy-build-config() {
  declare desc="build nginx config to proxy app containers from command line"
  declare trigger="proxy-build-config"
  declare APP="$1"

  echo "Proxy type:" "$(get_app_proxy_type "$APP"); PROXY_NAME: $PROXY_NAME"

  if [[ "$(get_app_proxy_type "$APP")" != "$PROXY_NAME" ]]; then
    echo "[trigger-nginx-custom-proxy-build-config] Quitting"
    return
  fi

  echo "DOKKU_LIB_ROOT: $DOKKU_LIB_ROOT"
  
  nginx_build_config "$APP"
  restart_nginx "$APP"
}

trigger-nginx-custom-proxy-build-config "$@"
