#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_DIR/config"
source "$_DIR/functions"
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

# Trap any errors and exit with DOKKU_FAIL_EXIT_CODE
trap 'exit ${DOKKU_FAIL_EXIT_CODE:-1}' ERR

trigger-nginx-custom-proxy-build-config() {
  declare desc="build nginx config to proxy app containers from command line"
  declare trigger="proxy-build-config"
  declare APP="$1"

  log_info "Running trigger trigger-nginx-custom-proxy-build-config"
  echo "Proxy type:" "$(get_app_proxy_type "$APP"); PROXY_NAME: $PROXY_NAME"

  if [[ "$(get_app_proxy_type "$APP")" != "$PROXY_NAME" ]]; then
    echo "[trigger-nginx-custom-proxy-build-config] Quitting"
    return
  fi

  nginx_build_config "$APP" || dokku_log_fail "nginx build config failed"
  restart_nginx "$APP" || dokku_log_fail "nginx restart failed"
}

trigger-nginx-custom-proxy-build-config "$@"