location ~\.php$ {
  fastcgi_cache fastcgi_some-app_in_mem;
  fastcgi_cache_valid 200 60m;
  fastcgi_cache_use_stale error timeout http_500;
  fastcgi_pass some-app-php_fpm;
  include fastcgi_params;
  
}


location / {
  try_files $uri $uri/ /index.php?$args;
  
}


location ~*\.(js|css|png|jpg|jpeg|gif|ico)$ {
  expires max;
  log_not_found off;
  
}

