map $http_x_api_key $some-app_user_tier {
  hostnames;
  default bronze;
  "~^premium-.*$" gold;
  "~^enterprise-.*$" platinum;
  
}
map $request_uri $some-app_cache_key {
  default $request_uri;
  "~^/api/v1/cached/.*$" "${request_uri}__${http_x_api_key}";
  
}
