proxy_cache_path /dev/shm/nginx/cache-in-mem/proxy_some-app_in_mem keys_zone=proxy_some-app_in_mem:10m ;
proxy_cache_path /tmp/nginx/cache/proxy_some-app_on_disk keys_zone=proxy_some-app_on_disk:10m ;