upstream some-app-5000 {
  server 172.17.0.2:5000 max_fails=3 fail_timeout=50s weight=1;
  server 172.17.0.3:5000 weight=1 max_fails=3 fail_timeout=50s;
  server 172.17.0.4:5000 fail_timeout=50s weight=1 max_fails=3;
}
upstream some-app-5001 {
  server 172.17.0.2:5001 weight=1 max_fails=3 fail_timeout=50s;
  server 172.17.0.3:5001 weight=1 max_fails=3 fail_timeout=50s;
  server 172.17.0.4:5001 max_fails=3 fail_timeout=50s weight=1;
}
upstream some-app-5002 {
  server 172.17.0.2:5002 weight=1 max_fails=3 fail_timeout=50s;
  server 172.17.0.3:5002 weight=1 max_fails=3 fail_timeout=50s;
  server 172.17.0.4:5002 fail_timeout=50s weight=1 max_fails=3;
}
upstream some-app-grpc_backend {
  server 127.0.0.1:9001 weight=1 max_fails=3 fail_timeout=50s;
  server 127.0.0.1:9002 weight=1 max_fails=3 fail_timeout=50s;
}
upstream some-app-php_fpm {
  server unix:/var/run/php/php8.1-fpm.sock weight=1 max_fails=3 fail_timeout=50s;
}
upstream some-app-static_backend {
  server 127.0.0.1:3000 weight=1 fail_timeout=50s max_fails=3;
  server 127.0.0.1:3001 backup weight=1 max_fails=3 fail_timeout=50s;
}
upstream some-app-websocket_proxy {
  server 127.0.0.1:8001 weight=1 max_fails=3 fail_timeout=50s;
  server 127.0.0.1:8002 fail_timeout=50s weight=1 max_fails=3;
  server 127.0.0.1:8003 backup weight=1 max_fails=3 fail_timeout=50s;
}
